version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "maxfischer2781"
    cooldown:
      default-days: 7
    groups:
      minor:
        update-types:
          - "minor"
      patches:
        update-types:
          - "patch"
